### ISSUE TITLE
Installation data folder wrong

### ISSUE THREAD

**Issue by cweiske** [pyrus/Pyrus#26]
## Description:

When installing PEAR2_Pyrus the data for the data folder is installed in the wrong location.
## Test script:

Create a new registry:
php pyrus.phar <registry_location> install PEAR2_Pyrus
php pyrus.phar <registry_location> list-channels

Goto:
<registry_location>\data\PEAR2_Pyrus\pear2.php.net\PEAR2_Pyrus\pear2.php.net
## Expected result:

Data files should be placed in:
<registry_location>\data\PEAR2_Pyrus\pear2.php.net\
## Actual result:

Data files are placed in:
<registry_location>\data\PEAR2_Pyrus\pear2.php.net\PEAR2_Pyrus\pear2.php.net

**Comment by cweiske** [comment]
This bug also cause the following problem:

Description:
When installing a package Using de OOP interface the following warning is displayed: Warning: DOMDocument::schemaValidate(): Invalid Schema in D:\pear\repo\php\PEAR2
\Pyrus\XMLParser.php on line 209

Expected result:
No warning

Actual result:
A warning because the schema file is not in the expected place on the filesystem.

**Comment by cweiske** [comment]
This bug also cause the following problem:
When installing a package Using de OOP interface the following exceptions are show:

Fatal error: Uncaught exception 'PEAR2\MultiErrors' with message 'multiple errors found' in D:\pear\repo\php\PEAR2\Pyrus\Channel\RemotePackage.php:337
Stack trace:
#0 D:\pear\repo\php\PEAR2\Pyrus\Package\Remote.php(155): PEAR2\Pyrus\Channel\RemotePackage->download()
#1 D:\pear\repo\php\PEAR2\Pyrus\Package.php(192): PEAR2\Pyrus\Package\Remote->download()
#2 D:\pear\repo\php\PEAR2\Pyrus\Installer.php(265): PEAR2\Pyrus\Package->download()
#3 D:\pear\packages\PackageManager\tests\i.php(10): PEAR2\Pyrus\Installer::commit()
#4 {main}

Next exception 'PEAR2\Pyrus\Package\Exception' with message 'Invalid abstract package pear2.php.net/PEAR2_Pyrus' in D:\pear\repo\php\PEAR2\Pyrus\Channel\RemotePackage.php:431
Stack trace:
#0 D:\pear\repo\php\PEAR2\Pyrus\Package\Remote.php(155): PEAR2\Pyrus\Channel\RemotePackage->download()
#1 D:\pear\repo\php\PEAR2\Pyrus\Package.php(192): PEAR2\Pyrus\Package\Remote->download()
#2 D:\pear\repo\php\PEAR2\Pyrus\Installer.php(265): PEAR2\Pyrus\Package->download()
#3 D:\pear\packages\PackageManager\tes in D:\pear\repo\php\PEAR2\Pyrus\Channel\RemotePackage.php on line 431

These are gone once i move the files in the right folder :D

**Comment by cweiske** [comment]
It looks like 'PEAR2_Console_CommandLine' and 'PEAR2_HTTP_Request' also have location placement bug but then for the docs and tests folders.

Also added the following bug: http://pear.php.net/bugs/bug.php?id=17590 (maybe i was a bit to quick)

**Comment by fpoirotte** [comment]
I can also reproduce this issue with any release of Phing (pyrus.phar i pear.phing.info/Phing).
Phing will not work out-of-the-box because the data files are installed at the wrong location, eg. phing/phing/listener/defaults.properties instead of just phing/listener/defaults.properties.

The package.xml file for Phing contains the following markup (shortened to display only the relevant parts):

```
    <contents>
      <dir baseinstalldir="phing" name="/">
          <file baseinstalldir="phing" md5sum="7fe4385efae327e7ecea4d80a5dad7be" name="listener/defaults.properties" role="data" />
      </dir>
    </contents>
```

**Comment by saltybeagle** [comment]
This issue was fixed in PEAR2_Pyrus-2.0.0a2

**Comment by fpoirotte** [comment]
Actually, I can still reproduce this issue while trying to install phing using a fresh git clone.
See my previous comment for symptoms of this problem.

**Comment by saltybeagle** [comment]
Aha, the issue was fixed for pyrus built packages. Older PEAR packages still have a doubling of the package name on the docs/data/etc dir.

**Comment by ashnazg** [comment]
I see this "doubling of the package name" condition occurring when installing pear/phpdocumentor using pyrus 2.0.0a3... my data_dir shows data/PhpDocumentor/PhpDocumentor when it should only show /data/PhpDocumentor.

However, I don't really see "doubling" occuring with other pear1 packages.  In considering other folders I see in data/:
- PEAR has loose files directly in data/PEAR/
- Codesniffer has a loose file in data/PHP_CodeSniffer/PHP/
- Structures_Graph has a loose file directly in data/Structures_Graph/
- XML_Serializer has loose files in data/XML_Serializer/doc

Perhaps it's not simply a matter of seeing PEAR1 package name dirs being doubled...

**Comment by saltybeagle** [comment]
Hmm, this could be due to the `baseinstalldir` option within the `package.xml`.

`baseinstalldir="PhpDocumentor"`

http://svn.php.net/viewvc/pear/packages/PhpDocumentor/trunk/package.xml?view=markup#l109

**Comment by ashnazg** [comment]
I see baseinstalldir="PhpDocumentor" all over the place.  Are you meaning all of them, only the ones on the files in role=data, all the file entries altogether, ... ?  In comparing it with XML_Util's package.xml, I see baseinstalldir only used on the top-level dir (dir baseinstalldir="XML" name="/").  Is that the more proper usage of baseinstalldir?

**Comment by ashnazg** [comment]
Comparing installations of PhpDocumentor in Pyrus (PHP 5.3.8) versus PEAR (5.2.17 and 4.4.9), I do see a doubling of the baseinstalldir occurring in only the data, docs, and tests role directories, only in the pyrus installation.  Granted, PhpDocumentor doesn't put anything in the other role dirs (e.g. www).

**Comment by fpoirotte** [comment]
The original bug report on pear.php.net has a patch (see http://pear.php.net/bugs/bug.php?id=17589&edit=12&patch=Xml.Role.Fix&revision=latest) that seems to do the trick for the "data" role, but somehow, this doesn't look like the right fix for this defect (it removes the "unusualbaseinstall" flag and sets the "honorsbaseinstall" flag instead).

Now I'm pretty sure the "unusualbaseinstall" flag was added for a reason (and the "data" role was given that flag for that very same reason).
Could someone with more knowledge please explain why this flag is necessary and how it affects installation paths?

Note: the "cfg", "doc", "src", "test" and "www" roles all use that flag (see Pyrus/Installer/Role/*.xml), so that the "script", "ext" and "php" roles are the only ones that use "honorsbaseinstall" instead of "unusualbaseinstall".

**Comment by cweiske** [comment]
This bug breaks phing and phpdocumentor.
